# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tango_panicfrontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmsGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouping', models.CharField(max_length=32, verbose_name='Grouping shema')),
                ('group', models.CharField(max_length=32, verbose_name='Group name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('query', models.CharField(max_length=255, verbose_name='URL query')),
            ],
        ),
        migrations.AlterField(
            model_name='alarmsfrontendsettingsmodel',
            name='panicapi_url_base',
            field=models.URLField(default='http://localhost:8000/panicapi', verbose_name='PANIC REST api URL'),
        ),
    ]
